name: Calidad

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  markdownlint:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: |
            **/*.md
            !**/LICENSE.md

  links:
    name: Enlaces
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --config .lychee.toml
            --verbose
            --no-progress
            './**/*.md'
          fail: true
